In [1]:
import pandas as pd 

df=pd.read_csv("pizza.csv")
df.head(5)

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

In [2]:
df.isnull().sum()

pizza_id             0
order_id             0
pizza_name_id        0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
dtype: int64

In [3]:
df.describe()

           pizza_id      order_id      quantity    unit_price   total_price
count  48620.000000  48620.000000  48620.000000  48620.000000  48620.000000
mean   24310.500000  10701.479761      1.019622     16.494132     16.821474
std    14035.529381   6180.119770      0.143077      3.621789      4.437398
min        1.000000      1.000000      1.000000      9.750000      9.750000
25%    12155.750000   5337.000000      1.000000     12.750000     12.750000
50%    24310.500000  10682.500000      1.000000     16.500000     16.500000
75%    36465.250000  16100.000000      1.000000     20.250000     20.500000
max    48620.000000  21350.000000      4.000000     35.950000     83.000000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_name_id      48620 non-null  str
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  str
 5   order_time         48620 non-null  str
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  str
 9   pizza_category     48620 non-null  str
 10  pizza_ingredients  48620 non-null  str
 11  pizza_name         48620 non-null  str
dtypes: float64(2), int64(3), str(7)
memory usage: 4.5 MB

In [6]:
df['order_date']=pd.to_datetime(df['order_date'])
df['order_time']=pd.to_datetime(df['order_time'],format='%H:%M:%S').dt.time
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_name_id      48620 non-null  str
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  datetime64[us]
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  str
 9   pizza_category     48620 non-null  str
 10  pizza_ingredients  48620 non-null  str
 11  pizza_name         48620 non-null  str
dtypes: datetime64[us](1), float64(2), int64(3), object(1), str(5)
memory usage: 4.5+ MB

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
pip install psycopg2 sqlalchemy ipykernel

Requirement already satisfied: psycopg2 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (2.0.43)
Requirement already satisfied: ipykernel in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (7.1.0)
Requirement already satisfied: greenlet>=1 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: comm>=0.1.1 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipykernel) (1.8.19)
Requirement already satisfied: ipython>=7.23.1 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipykernel) (9.9.0)
Requirement already satisfied: jupyter-client>=8.0.0 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipykernel) (8.8.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging>=22 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipykernel) (25.0)
Requirement already satisfied: psutil>=5.7 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipykernel) (7.2.1)
Requirement already satisfied: pyzmq>=25 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.2 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipykernel) (6.5.4)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipykernel) (5.14.3)
Requirement already satisfied: colorama>=0.4.4 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipython>=7.23.1->ipykernel) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from jupyter-client>=8.0.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel) (4.5.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from jedi>=0.18.1->ipython>=7.23.1->ipykernel) (0.8.5)
Requirement already satisfied: wcwidth in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.3.0)
Requirement already satisfied: six>=1.5 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.0.0->ipykernel) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\acer\appdata\local\programs\python\python312\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from sqlalchemy import create_engine

username='postgres'
password=
host='localhost'
port=
database='pizza'

engine=create_engine(f'postgresql://{username}:{password}@{host}:{port}/{database}')
table_name='pizza_sales'
df.to_sql(table_name, engine, if_exists='replace', index=False)
print("DataFrame has been successfully inserted into the PostgreSQL database.")

DataFrame has been successfully inserted into the PostgreSQL database.